### ISSUE TITLE
Usage examples

### ISSUE THREAD

**Issue by arnoldbird** [Kimaia/react-native-hyperlinked-text#4]
Thanks for this library.  It's working very well for me.  I'm wondering if the README needs updating.  I think the first usage example doesn't work... the one with the onLinkPress prop.  I get an error: "JSX value should be either an expression or a quoted JSX text".

Also, fwiw, here is a usage example for React Navigation, using react-native-hyperlinked-text to create a Crosslinked component with markdown syntax.  At least, I think this is the right approach... it seems to work:

```
import * as React from 'react'
import { Text } from 'react-native'
import { withNavigation } from 'react-navigation';
import HyperlinkedText from 'react-native-hyperlinked-text'

// In the Styles component I use https://facebook.github.io/react-native/docs/stylesheet.html
import styles from './Styles';

class Crosslinked extends React.Component {

  render() { 
    return (
      <Text><HyperlinkedText
        style={styles.link}
        linkDefs={[
          {
            style: styles.linktext,
            regex: /\[(.*?)\]\((.*?)\)/mgi,
            replaceText: (orig, text, route) => text,
            onPress: (orig, text, route) => this.props.navigation.navigate(route)
          }
        ]}>
          {this.props.children}
      </HyperlinkedText> </Text>
    )
  }
};

export default withNavigation(Crosslinked);

```
I am finding that to get a space after the link, I need to wrap HyperlinkedText in a Text component, as above, and have the closing tags be on the same line with a space between: 
`</HyperlinkedText> </Text>`
Thanks!

**Comment by daramasala** [comment]
Hi @arnoldbird ,
Thanks for your input. 
You mention 2 issues:
1. Update the usage examples. Can you open a PR with your updates?
2. Space at the end of the text is ignored. Am I correct?

**Comment by arnoldbird** [comment]
@daramasala 

With regard to #1, I'm probably not going to investigate why the first example doesn't work for me, because I don't need that code.  I'll report back if I have any insight.

As for #2, I am no longer having this issue.  I wonder if it may have been due to something in my styles.  Because I don't have this issue anymore, I was able to simplify my component a little...

```
import * as React from 'react'

import { withNavigation } from 'react-navigation';
import HyperlinkedText from 'react-native-hyperlinked-text'

class Crosslinked extends React.Component {

  render() { 
    return (
      <HyperlinkedText
        linkDefs={[
          {
            style: { 
              color: 'blue',
              textDecorationLine: 'underline', 
            },
            regex: /\[(.*?)\]\((.*?)\)/mgi,
            replaceText: (orig, text, route) => text,
            onPress: (orig, text, route) => this.props.navigation.navigate(route)
          }
        ]}>
          {this.props.children}
      </HyperlinkedText>
    )
  }
};

export default withNavigation(Crosslinked);
```

I will go ahead and close this ticket.  Thx!
